// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package blackbox

import (
	"github.com/dc0d/bank_account_kata_go/core/actions/boundaries"
	"github.com/dc0d/bank_account_kata_go/delivery/webapi"
	"sync"
)

var (
	lockDepositActionProviderSpyProvideDepositAction sync.RWMutex
)

// Ensure, that DepositActionProviderSpy does implement webapi.DepositActionProvider.
// If this is not the case, regenerate this file with moq.
var _ webapi.DepositActionProvider = &DepositActionProviderSpy{}

// DepositActionProviderSpy is a mock implementation of webapi.DepositActionProvider.
//
//     func TestSomethingThatUsesDepositActionProvider(t *testing.T) {
//
//         // make and configure a mocked webapi.DepositActionProvider
//         mockedDepositActionProvider := &DepositActionProviderSpy{
//             ProvideDepositActionFunc: func() boundaries.Action {
// 	               panic("mock out the ProvideDepositAction method")
//             },
//         }
//
//         // use mockedDepositActionProvider in code that requires webapi.DepositActionProvider
//         // and then make assertions.
//
//     }
type DepositActionProviderSpy struct {
	// ProvideDepositActionFunc mocks the ProvideDepositAction method.
	ProvideDepositActionFunc func() boundaries.Action

	// calls tracks calls to the methods.
	calls struct {
		// ProvideDepositAction holds details about calls to the ProvideDepositAction method.
		ProvideDepositAction []struct {
		}
	}
}

// ProvideDepositAction calls ProvideDepositActionFunc.
func (mock *DepositActionProviderSpy) ProvideDepositAction() boundaries.Action {
	if mock.ProvideDepositActionFunc == nil {
		panic("DepositActionProviderSpy.ProvideDepositActionFunc: method is nil but DepositActionProvider.ProvideDepositAction was just called")
	}
	callInfo := struct {
	}{}
	lockDepositActionProviderSpyProvideDepositAction.Lock()
	mock.calls.ProvideDepositAction = append(mock.calls.ProvideDepositAction, callInfo)
	lockDepositActionProviderSpyProvideDepositAction.Unlock()
	return mock.ProvideDepositActionFunc()
}

// ProvideDepositActionCalls gets all the calls that were made to ProvideDepositAction.
// Check the length with:
//     len(mockedDepositActionProvider.ProvideDepositActionCalls())
func (mock *DepositActionProviderSpy) ProvideDepositActionCalls() []struct {
} {
	var calls []struct {
	}
	lockDepositActionProviderSpyProvideDepositAction.RLock()
	calls = mock.calls.ProvideDepositAction
	lockDepositActionProviderSpyProvideDepositAction.RUnlock()
	return calls
}
